changelog-seen = 2

[llvm]
download-ci-llvm = false

[build]

[install]

[rust]

[target.x86_64-unknown-linux-gnu]
llvm-config = "/llvm-mos/build/bin/llvm-config"
llvm-has-rust-patches = false

[dist]
